# Sheriff configuration. All available keys and their defaults are in .sheriff/config.yaml.

append:
    infra.exclude:
        - docs

override:
    php_cs_fixer.extend: "        'phpdoc_types' => ['groups' => ['meta', 'simple', 'alias'], 'exclude' => ['scalar', 'integer']],"
    phpmetrics.coupling.max_afferent: 30
    phpstan.parameters:
        haspadar:
            afferentCoupling:
                maxAfferent: 10
                ignoreInterfaces: true
                excludedClasses:
                    - Primus\Text\TextOf
                    - Primus\Text\Mapped
                    - Primus\Func\FuncOf
                    - Primus\Scalar\ScalarOf
    phpunit.testsuites.unit: ["../../tests"]
    phpunit.testsuites.integration: []
    ci.pr.max_lines_changed: 500
