coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%

    patch:
      default:
        target: 95%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
